<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<StaticWebAssetBasePath>_content/MyCOLL.UIComponents</StaticWebAssetBasePath>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="8.0.2" />
		<PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="8.0.0" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.0.3" />
	</ItemGroup>

	<ItemGroup>
		<None Include="wwwroot\**" Pack="true" PackagePath="staticwebassets" />
	</ItemGroup>

</Project>