<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="wwwroot\css\app.css" />
    <Content Remove="wwwroot\css\rustic.css" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Components\Pages\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\css\app.css">
      <PackagePath>staticwebassets</PackagePath>
      <Pack>true</Pack>
    </None>
    <None Include="wwwroot\css\rustic.css">
      <PackagePath>staticwebassets</PackagePath>
      <Pack>true</Pack>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MyCOLL.Razor\MyCOLL.UIComponents.csproj" />
  </ItemGroup>

</Project>
